# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprofile.proto\x12\x07profile\"\x1b\n\x07Request\x12\x10\n\x08hotelIds\x18\x01 \x03(\t\"(\n\x06Result\x12\x1e\n\x06hotels\x18\x01 \x03(\x0b\x32\x0e.profile.Hotel\"\x8e\x01\n\x05Hotel\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bphoneNumber\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12!\n\x07\x61\x64\x64ress\x18\x05 \x01(\x0b\x32\x10.profile.Address\x12\x1e\n\x06images\x18\x06 \x03(\x0b\x32\x0e.profile.Image\"\x8f\x01\n\x07\x41\x64\x64ress\x12\x14\n\x0cstreetNumber\x18\x01 \x01(\t\x12\x12\n\nstreetName\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\x12\x12\n\npostalCode\x18\x06 \x01(\t\x12\x0b\n\x03lat\x18\x07 \x01(\x02\x12\x0b\n\x03lon\x18\x08 \x01(\x02\"%\n\x05Image\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\x02 \x01(\x08\x32;\n\x07Profile\x12\x30\n\x0bGetProfiles\x12\x10.profile.Request\x1a\x0f.profile.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profile_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=26
  _globals['_REQUEST']._serialized_end=53
  _globals['_RESULT']._serialized_start=55
  _globals['_RESULT']._serialized_end=95
  _globals['_HOTEL']._serialized_start=98
  _globals['_HOTEL']._serialized_end=240
  _globals['_ADDRESS']._serialized_start=243
  _globals['_ADDRESS']._serialized_end=386
  _globals['_IMAGE']._serialized_start=388
  _globals['_IMAGE']._serialized_end=425
  _globals['_PROFILE']._serialized_start=427
  _globals['_PROFILE']._serialized_end=486
# @@protoc_insertion_point(module_scope)
