# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import rate_pb2 as rate__pb2


class RateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRates = channel.unary_unary(
                '/rate.Rate/GetRates',
                request_serializer=rate__pb2.Request.SerializeToString,
                response_deserializer=rate__pb2.Result.FromString,
                )


class RateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRates(self, request, context):
        """GetRates returns rate codes for hotels for a given date range
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRates,
                    request_deserializer=rate__pb2.Request.FromString,
                    response_serializer=rate__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rate.Rate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Rate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rate.Rate/GetRates',
            rate__pb2.Request.SerializeToString,
            rate__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
