# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/feature.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/feature.proto\x12\x07\x66\x65\x61ture\"1\n\x0e\x46\x65\x61tureRequest\x12\x0f\n\x07imageId\x18\x01 \x01(\t\x12\x0e\n\x06kernel\x18\x02 \x01(\x05\"!\n\x0f\x46\x65\x61tureResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32G\n\x07\x46\x65\x61ture\x12<\n\x07\x45xtract\x12\x17.feature.FeatureRequest\x1a\x18.feature.FeatureResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.feature_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FEATUREREQUEST']._serialized_start=32
  _globals['_FEATUREREQUEST']._serialized_end=81
  _globals['_FEATURERESPONSE']._serialized_start=83
  _globals['_FEATURERESPONSE']._serialized_end=116
  _globals['_FEATURE']._serialized_start=118
  _globals['_FEATURE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
