# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/search.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/search.proto\x12\x06search\"2\n\rSearchRequest\x12\x0e\n\x06kernel\x18\x01 \x01(\x05\x12\x11\n\tthreshold\x18\x02 \x01(\x02\"\"\n\x0eSearchResponse\x12\x10\n\x08imageIds\x18\x01 \x03(\t2A\n\x06Search\x12\x37\n\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEARCHREQUEST']._serialized_start=30
  _globals['_SEARCHREQUEST']._serialized_end=80
  _globals['_SEARCHRESPONSE']._serialized_start=82
  _globals['_SEARCHRESPONSE']._serialized_end=116
  _globals['_SEARCH']._serialized_start=118
  _globals['_SEARCH']._serialized_end=183
# @@protoc_insertion_point(module_scope)
