# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/similarity.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/similarity.proto\x12\nsimilarity\";\n\x11SimilarityRequest\x12\x13\n\x0bqueryVector\x18\x01 \x03(\x02\x12\x11\n\tthreshold\x18\x02 \x01(\x02\"&\n\x12SimilarityResponse\x12\x10\n\x08imageIds\x18\x01 \x03(\t2S\n\nSimilarity\x12\x45\n\x04\x46ind\x12\x1d.similarity.SimilarityRequest\x1a\x1e.similarity.SimilarityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.similarity_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SIMILARITYREQUEST']._serialized_start=38
  _globals['_SIMILARITYREQUEST']._serialized_end=97
  _globals['_SIMILARITYRESPONSE']._serialized_start=99
  _globals['_SIMILARITYRESPONSE']._serialized_end=137
  _globals['_SIMILARITY']._serialized_start=139
  _globals['_SIMILARITY']._serialized_end=222
# @@protoc_insertion_point(module_scope)
