# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgeo.proto\x12\x03geo\"#\n\x07Request\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\"\x1a\n\x06Result\x12\x10\n\x08hotelIds\x18\x01 \x03(\t2*\n\x03Geo\x12#\n\x06Nearby\x12\x0c.geo.Request\x1a\x0b.geo.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=18
  _globals['_REQUEST']._serialized_end=53
  _globals['_RESULT']._serialized_start=55
  _globals['_RESULT']._serialized_end=81
  _globals['_GEO']._serialized_start=83
  _globals['_GEO']._serialized_end=125
# @@protoc_insertion_point(module_scope)
