# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrate.proto\x12\x04rate\"<\n\x07Request\x12\x10\n\x08hotelIds\x18\x01 \x03(\t\x12\x0e\n\x06inDate\x18\x02 \x01(\t\x12\x0f\n\x07outDate\x18\x03 \x01(\t\"+\n\x06Result\x12!\n\tratePlans\x18\x01 \x03(\x0b\x32\x0e.rate.RatePlan\"l\n\x08RatePlan\x12\x0f\n\x07hotelId\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0e\n\x06inDate\x18\x03 \x01(\t\x12\x0f\n\x07outDate\x18\x04 \x01(\t\x12 \n\x08roomType\x18\x05 \x01(\x0b\x32\x0e.rate.RoomType\"\x88\x01\n\x08RoomType\x12\x14\n\x0c\x62ookableRate\x18\x01 \x01(\x01\x12\x11\n\ttotalRate\x18\x02 \x01(\x01\x12\x1a\n\x12totalRateInclusive\x18\x03 \x01(\x01\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x17\n\x0froomDescription\x18\x06 \x01(\t2/\n\x04Rate\x12\'\n\x08GetRates\x12\r.rate.Request\x1a\x0c.rate.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=20
  _globals['_REQUEST']._serialized_end=80
  _globals['_RESULT']._serialized_start=82
  _globals['_RESULT']._serialized_end=125
  _globals['_RATEPLAN']._serialized_start=127
  _globals['_RATEPLAN']._serialized_end=235
  _globals['_ROOMTYPE']._serialized_start=238
  _globals['_ROOMTYPE']._serialized_end=374
  _globals['_RATE']._serialized_start=376
  _globals['_RATE']._serialized_end=423
# @@protoc_insertion_point(module_scope)
