# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"J\n\rNearbyRequest\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\x12\x0e\n\x06inDate\x18\x03 \x01(\t\x12\x0f\n\x07outDate\x18\x04 \x01(\t\" \n\x0cSearchResult\x12\x10\n\x08hotelIds\x18\x01 \x03(\t2?\n\x06Search\x12\x35\n\x06Nearby\x12\x15.search.NearbyRequest\x1a\x14.search.SearchResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_NEARBYREQUEST']._serialized_start=24
  _globals['_NEARBYREQUEST']._serialized_end=98
  _globals['_SEARCHRESULT']._serialized_start=100
  _globals['_SEARCHRESULT']._serialized_end=132
  _globals['_SEARCH']._serialized_start=134
  _globals['_SEARCH']._serialized_end=197
# @@protoc_insertion_point(module_scope)
