# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/metadata.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/metadata.proto\x12\x08metadata\"#\n\x0fMetadataRequest\x12\x10\n\x08imageIds\x18\x01 \x03(\t\"3\n\tImageMeta\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\"7\n\x10MetadataResponse\x12#\n\x06images\x18\x01 \x03(\x0b\x32\x13.metadata.ImageMeta2H\n\x08Metadata\x12<\n\x03Get\x12\x19.metadata.MetadataRequest\x1a\x1a.metadata.MetadataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.metadata_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_METADATAREQUEST']._serialized_start=34
  _globals['_METADATAREQUEST']._serialized_end=69
  _globals['_IMAGEMETA']._serialized_start=71
  _globals['_IMAGEMETA']._serialized_end=122
  _globals['_METADATARESPONSE']._serialized_start=124
  _globals['_METADATARESPONSE']._serialized_end=179
  _globals['_METADATA']._serialized_start=181
  _globals['_METADATA']._serialized_end=253
# @@protoc_insertion_point(module_scope)
