name: 'Add swarm workers - horizontal scaling'

on:
  workflow_dispatch:
    inputs:
      swarm_workers_count:
        description: 'Number of swarm workers (1 or 3)'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '3'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      TF_VAR_swarm_worker_token: ${{ secrets.SWARM_WORKER_TOKEN }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
      TF_VAR_swarm_workers_count: ${{ github.event.inputs.swarm_workers_count }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Auth gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GOOGLE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform -chdir="./terraform" init

      - name: Terraform Plan
        run: terraform -chdir="./terraform" plan
  
      - name: Terraform Apply
        run: terraform -chdir="./terraform" apply -auto-approve -input=false
