version: '3.8'

services:
  gateway:
    image: ghcr.io/wiktorczetyrbok/microservices-monoliths-comp/js-gateway-grpc:latest
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - search
      - profile
    networks:
      - app-network

  search:
    image: ghcr.io/wiktorczetyrbok/microservices-monoliths-comp/js-search-grpc:latest
    build:
      context: ./search
      dockerfile: Dockerfile
    networks:
      - app-network

  profile:
    image: ghcr.io/wiktorczetyrbok/microservices-monoliths-comp/js-profile-grpc:latest
    build:
      context: ./profile
      dockerfile: Dockerfile
    networks:
      - app-network

  geo:
    image: ghcr.io/wiktorczetyrbok/microservices-monoliths-comp/js-geo-grpc:latest
    build:
      context: ./geo
      dockerfile: Dockerfile
    networks:
      - app-network

  rate:
    image: ghcr.io/wiktorczetyrbok/microservices-monoliths-comp/js-rate-grpc:latest
    build:
      context: ./rate
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
